---
kind: Service
apiVersion: v1
metadata:
  name: apostle-app-be-lb
spec:
  type: LoadBalancer
  selector:
    app: apostle-app-be
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 80
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: apostle-be-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apostle-app-be
  template:
    metadata:
      labels:
        app: apostle-app-be
    spec:
      containers:
      - name: apostle-be
        image: registry.digitalocean.com/apostle-docker-registry/apostle-be:late  
        ports:
        - containerPort: 5000
          protocol: TCP