name : Build the app to digital ocean registry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@main
      - name: Build image 
        run: docker build -t apostle/be  .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag apostle/be \registry.digitalocean.com/apostle-docker-registry/apostle-be:latest
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/apostle-docker-registry/apostle-be:latest  
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 01b1870c-dbec-4bc7-8d4f-edb81899f516   
      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/manifest.yaml
