name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        env:
          host: ${{ secrets.HOST }}
          username: 'root'
          key: ${{ secrets.BACK_END_KEY}}
          port: 22
        with:
          script: |
           cd /root/apotek-app-fe/
           ls
