name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: master
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: 'root'
          key: ${{ secrets.BACK_END_SECRET_KEY}}
          port: 22
          script: |
           cd /root/Apostle/
           ${{secrets.CODE_SCRIPT}}
